export const LOGIN= 'LOGIN';
export const REGISTER= 'REGISTER';
export const LOGOUT= 'LOGOUT';

export const START_LOADING='START_LOADING';
export const END_LOADING='END_LOADING';


export const FETCH_ALL_ARTICLES= 'FETCH_ALL_ARTICLES';
export const FETCH_ARTICLE= 'FETCH_ARTICLE';
export const FETCH_ARTICLE_BY_SEARCH= 'FETCH_ARTICLE_BY_SEARCH';

export const FETCH_ALL_BOOK= 'FETCH_ALL_BOOK';
export const FETCH_BOOK= 'FETCH_BOOK';
export const FETCH_BOOK_BY_SEARCH= 'FETCH_BOOK_BY_SEARCH';

export const FETCH_ALL_VIDEOS= 'FETCH_ALL_VIDEOS';
export const FETCH_VIDEO= 'FETCH_VIDEO';
export const FETCH_VIDEO_BY_SEARCH= 'FETCH_VIDEO_BY_SEARCH';